# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SwiftAnimation
  pod 'NAExtensions', '~> 1.0.4'
  pod 'SnapKit'
end
